apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: pg-store
  namespace: postgres-cnpg
spec:
  configuration:
    destinationPath: s3://trk-k8s-pg-backups/
    s3Credentials:
      accessKeyId:
        name: aws-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: aws-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: "7d"
