secretsprovider: azurekeyvault://kv-trk-k8s-f92a7ab3.vault.azure.net/keys/pulumi-secrets
encryptedkey: bTRKNFptMDRkaEc3QjdxbGpPY3BMTTNMa2lqUjFmeXhTQjVfYlphZnRqRERibHJwRVBNbjYtdGxVc3AwQUlvSU1DN2s2cVFSbDZXNFJWZjJJcHRKNGVqZE0zUmNiYnFBaHAtMXE5enBfck1QVXR4OHk1WFdEc092bFd3alJoNUFJRmFYeDlDMkpiaS1KbjhZXzQ2QnZMQUhBTEp1c0Y0LUVOaUFtSXVhcFVPRWc0Ni01RUNTRHNuaEFxS3RtRlB0ak4zOTVXbFJ1Q0I0MkpjU3gybjlQWFV0alJjZmllX2h5aDNDaHpjaXU3UnRULWdiZFVSRkxTckpmZUlvb1VzZ013SU5qX1VnX2E1dU51cXMzQnRkNjlmNThYaUN4MmpHaDJ3Y0wwNnVXaHdNRUJXeTZuSjVYXzRCVzFOUU5wLXBVdTBqLVNYQkc0RHNId0RpbUItbTZB
config:
  trk-k8s-azure:myIp: 165.162.31.50/32
  trk-k8s-azure:sshPublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGOB9MhkVD2cuSSycPIqiSna0oSbTfbHc9/6/tBBy7Xw tkahng-k8s-azure
  azure-native:location: eastus
  trk-k8s-azure:subscriptionId: 85f3b630-afa5-42cf-b8b3-b06abbf5a28f
  trk-k8s-azure:persistRg: rg-trk-k8s-persistent
  trk-k8s-azure:backupStorageAccount: sttrkk8sf92a7ab3
  trk-k8s-azure:backupContainer: pg-backups
  trk-k8s-azure:nodeIdentityId: /subscriptions/85f3b630-afa5-42cf-b8b3-b06abbf5a28f/resourcegroups/rg-trk-k8s-persistent/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-trk-k8s-node
